## 개발(로컬) 환경 설정

redis:
  host: localhost

custom:
  site:
    frontUrl: "http://localhost:3000"
    backUrl: "http://localhost:${server.port}"

cookie:
  domain: "localhost"

profile:
  use_s3: false

